source 'https://rubygems.org'

gem 'bundler'
gem 'rake'
gem 'hanami',       '0.7.2'
gem 'hanami-model', '~> 0.5'

gem 'pg'
gem 'sass'

group :test do
  gem 'rspec'
  gem 'capybara'
end

group :test, :development do
  gem 'byebug'
end

group :production do
  # gem 'puma'
end
